[project]
name = "work-helper-kia"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "alembic==1.20.0",
    "docxtpl>=0.20.2",
    "flet[all]>=1.0.4",
    "pydantic-settings>=2.15.0",
    "python-docx>=1.2.0",
    "sqlalchemy[asyncio]>=2.1.4",
    "sqlmodel>=0.0.48",
]

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pyright>=1.1.414",
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]

[tool.mypy]
python_version = "3.14"  # Укажите вашу версию Python
# Исключаем всю папку с миграциями (укажите её реальное имя, например alembic или migrations)
mypy_path = "src"
exclude = [
    "^alembic/",
]

[[tool.mypy.overrides]]
module = "docxtpl.*"
ignore_missing_imports = true


[tool.pyright]
pythonVersion = "3.14"
include = ["src", "tests"]
exclude = ["**/__pycache__", ".venv"]
typeCheckingMode = "basic"  # "off", "basic" или "strict"
venvPath = "."       # Искать в текущей корневой папке проекта
venv = ".venv"       # Название папки виртуального окружения, которое создал `uv`

reportUnknownMemberType = false


[tool.black]
line-length = 100
target-version = ['py314']

[tool.ruff]
line-length = 100

# Настройка для pytest
[tool.pytest.ini_options]
# Указывает pytest добавить папку src в пути импорта (sys.path)
pythonpath = ["src"]
# Опционально: где искать тесты
testpaths = ["tests"]